name: Deploy LaTeX document
on:
  push:
    branches:
      - master
jobs:
  build_resume:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Git Client
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Compile LaTeX document (Resume)
        uses: xu-cheng/latex-action@master
        with:
          root_file: resume.tex
          args: -xelatex -file-line-error -interaction=nonstopmode -outdir=out
      - name: Compile LaTeX document (Resume One Page)
        uses: xu-cheng/latex-action@master
        with:
          root_file: resume-onepage.tex
          args: -xelatex -file-line-error -interaction=nonstopmode -outdir=out
      - name: Compile LaTeX document (CV)
        uses: xu-cheng/latex-action@master
        with:
          root_file: cv.tex
          args: -xelatex -file-line-error -interaction=nonstopmode -outdir=out
      - name: Compile LaTeX document (CV EU)
        uses: xu-cheng/latex-action@master
        with:
          root_file: cv-eu.tex
          args: -xelatex -file-line-error -interaction=nonstopmode -outdir=out

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: '${{ env.BRANCH }}'
          path: 'deploy'

      - name: Commit and Push Changes
        working-directory: ${{ github.workspace }}
        run: |
          mv deploy/.git deploy-git
          rm -rf deploy

          mv out/*.pdf deploy/
          mv deploy-git deploy/.git
          cd deploy

          git add .
          git commit -m "Update Artifacts"
          git push --force origin ${{ env.BRANCH }}
