name: Build LaTeX document
on: [push]
jobs:
  build_resume:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: resume.tex
          args: -xelatex -file-line-error -interaction=nonstopmode -outdir=out
      - name: Upload .PDF Artifact
        uses: actions/upload-artifact@v1
        with:
          name: resume
          path: out/resume.pdf
  build_cv:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: cv.tex
          args: -xelatex -file-line-error -interaction=nonstopmode -outdir=out
      - name: Upload .PDF Artifact
        uses: actions/upload-artifact@v1
        with:
          name: cv
          path: out/cv.pdf
