name: Build LaTeX document and publish artifact
on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!deploy'   # excludes deploy branch
jobs:
  build_resume:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: resume.tex
          args: -xelatex -file-line-error -interaction=nonstopmode -outdir=out
      - name: Upload .PDF Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Resume
          path: out/resume.pdf
  build_resume-onepage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: resume-onepage.tex
          args: -xelatex -file-line-error -interaction=nonstopmode -outdir=out
      - name: Upload .PDF Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Resume (One Page)
          path: out/resume-onepage.pdf
  build_cv:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: cv.tex
          args: -xelatex -file-line-error -interaction=nonstopmode -outdir=out
      - name: Upload .PDF Artifact
        uses: actions/upload-artifact@v1
        with:
          name: CV
          path: out/cv.pdf
  build_cv-eu:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: cv-eu.tex
          args: -xelatex -file-line-error -interaction=nonstopmode -outdir=out
      - name: Upload .PDF Artifact
        uses: actions/upload-artifact@v1
        with:
          name: CV (EU)
          path: out/cv-eu.pdf
